### ISSUE TITLE
Pontos de melhoria

### ISSUE THREAD

**Issue by CarlosCFO** [serviceticst/glpi-plugin-custom_login#1]
Após uma análise inicial, identifiquei os seguintes pontos importantes a serem considerados:

-É recomendável indicar o tamanho (em pixels) dos arquivos de imagem, especialmente em casos de logos não quadrados.
-Ser capaz de personalizar (ou remover) o link que aparece no rodapé da página (isso seria uma vantagem).
-Seria recomendável ter a opção de ativar/desativar a imagem de fundo.

**Comment by serviceticst** [comment]
Olá, Carlos, obrigado pelas recomendações. 

O tamanho da logo é recomenda 192 X 192, já adicionamos maiores e ficou legal.
Sobre o link, podemos pensar em uma nova versão do plugin. 
As imagens de fundos vai de acordo a sua necessidade de visualização no modo responsivo, dai teria que ir testando.
