### ISSUE TITLE
Disponible en 10.0.6 ? 

### ISSUE THREAD

**Issue by ajota21** [serviceticst/glpi-plugin-custom_login#2]
Esta disponible para la versión 10.0.6 ? porque al momento de cargar imagenes no me lo muestra en el login 

![image](https://user-images.githubusercontent.com/114438238/232071592-0b5f55e4-2ab0-4492-90db-e31175a7ab6d.png)

**Comment by jaimecabrito01** [comment]
A imagem que eu coloco em logo,não aparece o na tela de login.Poderia me ajudar?

**Comment by serviceticst** [comment]
Disponivel sim, tentou limpar o cache? (pt-br)

**Comment by serviceticst** [comment]
Debido a la falta de comentarios, cerraremos este problema.
