### ISSUE TITLE
Logo não aparece.

### ISSUE THREAD

**Issue by jaimecabrito01** [serviceticst/glpi-plugin-custom_login#3]
A imagem que eu coloco em logo,não aparece  na tela de login.Poderia me ajudar?

**Comment by serviceticst** [comment]
Olá, Jaime, tente limpar o cache do navegador.

**Comment by jaimecabrito01** [comment]
Limpei,mas não funcionou.

**Comment by serviceticst** [comment]
Jaime, tente ver esse vídeo para ver se ajuda. 

[https://www.youtube.com/watch?v=RXRI3FFQrGs](url)

**Comment by serviceticst** [comment]
Jaime, com o video enviando anteriomente, acredito que resolveu, estamos fechando essa issue.
