### ISSUE TITLE
Modification

### ISSUE THREAD

**Issue by Walter-49** [serviceticst/glpi-plugin-custom_login#4]
Bonjour,

Merci pour ce plugin, je cherchais une solution identique depuis longtemps. J'aimerais savoir comment faire pour supprimer  l'image "background font" et centrer en milieu de page  la demande de connexion.
Merci
![2023-05-08_123249](https://user-images.githubusercontent.com/57492116/236802255-c48fc6c6-79ba-4987-961a-d22344ce699a.png)

**Comment by serviceticst** [comment]
Bonjour, bonjour, s'il vous plaît, nous y travaillons pour de nouvelles mises à jour et possibilités, pour l'instant il n'est pas possible de personnaliser via plugin, uniquement via CSS depuis glpi (imprimer ci-dessous) ou en changeant le code source de l'outil.

![image](https://user-images.githubusercontent.com/70910492/236807873-30288ab4-0053-4cb2-81a3-f7a0fcb2161b.png)
