### ISSUE TITLE
Imagens não carregam no 10.0.9

### ISSUE THREAD

**Issue by romulloalves** [serviceticst/glpi-plugin-custom_login#5]
Olá, não estou conseguindo carregar as imagens no GLPI 10.0.9. Já tentei por vários navegadores, limpei o cache e cedi à permissão do diretório do plugin ao servidor web.

![image](https://github.com/serviceticst/glpi-plugin-custom_login/assets/142533916/ea2a4868-7077-4311-b5c5-93d100f508db)

**Comment by mauriciomagalhaes** [comment]
to com o mesmo, problema no 10.0.10, porem no 10.0.9 eu consegui.

**Comment by mauriciomagalhaes** [comment]
Tirei da pasta marketplace e coloquei na plugin e funcionou

**Comment by serviceticst** [comment]
Boa tarde, pessoal.

Vejam se o vídeo abaixo ajuda. 

[https://www.youtube.com/watch?v=RXRI3FFQrGs](url)

**Comment by reisdiegoss** [comment]
Aqui não altera a logo do menu

**Comment by serviceticst** [comment]
Reis, veja esse vídeo, deve te ajudar. 

[https://www.youtube.com/watch?v=RXRI3FFQrGs&list=PLwXxs1htu2adKC2f9mH1mx0HZ0qKJgnqw&index=9&t](url)
